DROP TABLE IF EXISTS DIAGNOSTICS_DOMAINS;
DROP TABLE IF EXISTS DIAGNOSTICS_SEEDS;
DROP TABLE IF EXISTS DIAGNOSTIC_TRACE;

DELETE FROM PLUGINS WHERE NAME = 'DIAGNOSTICS';
DELETE FROM MENUSECTIONS WHERE TRANSLATIONCODE IN ('menu-section-diagnostics');
DELETE FROM MENUENTRIES WHERE TRANSLATIONCODE IN ('menu-entries-diagnostics');

INSERT INTO PLUGINS(PLUGIN, NAME) VALUES ('DIAGNOSTICS', 'diagnostics-name');
INSERT INTO MENUSECTIONS (TRANSLATIONCODE, PLUGIN) VALUES ('menu-section-diagnostics', 'DIAGNOSTICS');
INSERT INTO MENUENTRIES (TRANSLATIONCODE, SLUG, SECTION, PLUGIN) VALUES ('menu-entries-diagnostics', '/diagnostics', 'menu-section-diagnostics', 'DIAGNOSTICS');
INSERT INTO MENUENTRIES (TRANSLATIONCODE, SLUG, SECTION, PLUGIN) VALUES ('menu-entries-domains', '/diagnostics/domains', 'menu-section-diagnostics', 'DIAGNOSTICS');

CREATE TABLE DIAGNOSTICS_DOMAINS(
    DOMAIN VARCHAR(255),
    VERIFICATOR TEXT,
    VALIDATED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DIAGNOSTICS_DOMAINS PRIMARY KEY(DOMAIN)
);

CREATE TABLE DIAGNOSTICS_SEEDS(
    ID INT,
    DOMAIN VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DIAGNOSTIC_SEEDS PRIMARY KEY(ID),
    CONSTRAINT FK_DIAGNOSTIC_SEEDS FOREIGN KEY(DOMAIN) REFERENCES DIAGNOSTICS_DOMAINS(DOMAIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DIAGNOSTICS_TRACE(
    ID INT AUTO_INCREMENT,
    TRACE TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DIAGNOSTIC_TRACE PRIMARY KEY(ID)
);