INSERT INTO PLUGINS(PLUGIN, NAME) VALUES ('EDITOR', 'editor-name');

DROP TABLE IF EXISTS USEREDITORCONFIG;
CREATE TABLE USEREDITORCONFIG(
    USER VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USEREDITORCONFIG PRIMARY KEY(USER),
    CONSTRAINT FK_USEREDITORCONFIG01 FOREIGN KEY(USER) REFERENCES USERS(NAME) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS EDITORPANELS;
CREATE TABLE EDITORPANELS(
    PANEL VARCHAR(100) NOT NULL,
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EDITORPANELS PRIMARY KEY(PANEL)
);

INSERT INTO EDITORPANELS(PANEL, DESCRIPTION) VALUES ('editor-panel-component-options', 'editor-panel-component-options-description');
INSERT INTO EDITORPANELS(PANEL, DESCRIPTION) VALUES ('editor-panel-component-reference', 'editor-panel-component-reference-description');
INSERT INTO EDITORPANELS(PANEL, DESCRIPTION) VALUES ('editor-panel-component-tree-structure', 'editor-panel-component-tree-structure-description');
INSERT INTO EDITORPANELS(PANEL, DESCRIPTION) VALUES ('editor-panel-component-list', 'editor-panel-component-list-description');

DROP TABLE IF EXISTS USEREDITORPANELS;
CREATE TABLE USEREDITORPANELS(
    USER VARCHAR(50) NOT NULL,
    PANEL VARCHAR(100) NOT NULL,
    SIDE SMALLINT DEFAULT 0,
    PANELORDER SMALLINT DEFAULT 0,
    VISIBLE SMALLINT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USEREDITORPANELS PRIMARY KEY(USER, PANEL),
    CONSTRAINT FK_USEREDITORPANELS01 FOREIGN KEY(USER) REFERENCES USERS(NAME) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_USEREDITORPANELS02 FOREIGN KEY(PANEL) REFERENCES EDITORPANELS(PANEL) ON DELETE CASCADE ON UPDATE CASCADE
);