-- Execute this sql script before the page installation
DROP DATABASE IF EXISTS BUILDER;
CREATE DATABASE BUILDER;

USE BUILDER;

DROP USER IF EXISTS 'superadmin'@'localhost';
CREATE USER IF NOT EXISTS 'superadmin'@'localhost' IDENTIFIED BY 'ucrUzsibq5HOKC5ZVlpg1nRIc';
GRANT ALL PRIVILEGES ON BUILDER.* TO 'superadmin'@'localhost';

CREATE TABLE ROLES (
    ROLE VARCHAR(50) NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE USERS(
    NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100),
    EMAIL VARCHAR(100),
    ROLE VARCHAR(50),
    BLOCKED SMALLINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BLOCKED_AT TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY(NAME),
    CONSTRAINT FK_USERS01 FOREIGN KEY(ROLE) REFERENCES ROLES(ROLE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE USERSACCESS(
    ID INTEGER AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY(ID),
    CONSTRAINT FK_USERSACCESS01 FOREIGN KEY(NAME) REFERENCES USERS(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO USERS (NAME, PASSWORD) VALUES ('Initial', '827ccb0eea8a706c4c34a16891f84e7b'); -- 12345