DROP TABLE IF EXISTS CONFIGURATION;

CREATE TABLE CONFIGURATION(
    NAME VARCHAR(50),
    VALUE VARCHAR(150),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONFIGURATION PRIMARY KEY(NAME)
);

DELETE FROM USERS WHERE NAME <> 'Initial';

INSERT INTO ROLES(ROLE) VALUES ('SuperAdmin');
INSERT INTO ROLES(ROLE) VALUES ('Admin');
INSERT INTO ROLES(ROLE) VALUES ('Editor');
INSERT INTO ROLES(ROLE) VALUES ('Guest');