DROP TABLE IF EXISTS CONFIGURATION;

CREATE TABLE CONFIGURATION(
    NAME VARCHAR(50),
    VALUE VARCHAR(150),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONFIGURATION PRIMARY KEY(NAME)
);

DELETE FROM USERS WHERE NAME <> 'Initial';

INSERT INTO ROLES(ROLE) VALUES ('SuperAdmin');
INSERT INTO ROLES(ROLE) VALUES ('Admin');
INSERT INTO ROLES(ROLE) VALUES ('Editor');
INSERT INTO ROLES(ROLE) VALUES ('Guest');

DROP TABLE IF EXISTS MENUSECTIONS;
CREATE TABLE MENUSECTIONS(
    TRANSLATIONCODE VARCHAR(100) NOT NULL,
    ISPLUGIN SMALLINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MENUSECTIONS PRIMARY KEY(TRANSLATIONCODE)
);

DROP TABLE IF EXISTS MENUENTRIES;
CREATE TABLE MENUENTRIES(
    TRANSLATIONCODE VARCHAR(100),
    SECTION VARCHAR(100),
    ISPLUGIN SMALLINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MENUENTRIES PRIMARY KEY(TRANSLATIONCODE),
    CONSTRAINT FK_MENUENTRIES01 FOREIGN KEY(SECTION) REFERENCES MENUSECTIONS(TRANSLATIONCODE)
);

INSERT INTO MENUSECTIONS (TRANSLATIONCODE) VALUES ('menu-section-access');
INSERT INTO MENUSECTIONS (TRANSLATIONCODE) VALUES ('menu-section-pages');
INSERT INTO MENUSECTIONS (TRANSLATIONCODE) VALUES ('menu-section-configuration');

INSERT INTO MENUENTRIES (TRANSLATIONCODE, SECTION) VALUES ('menu-entries-users', 'menu-section-access');
INSERT INTO MENUENTRIES (TRANSLATIONCODE, SECTION) VALUES ('menu-entries-privileges', 'menu-section-access');
INSERT INTO MENUENTRIES (TRANSLATIONCODE, SECTION) VALUES ('menu-entries-pages', 'menu-section-pages');
INSERT INTO MENUENTRIES (TRANSLATIONCODE, SECTION) VALUES ('menu-entries-languages', 'menu-section-configuration');

DROP TABLE IF EXISTS MENURESTRICTIONS;
CREATE TABLE MENURESTRICTIONS(
    USER VARCHAR(50) NOT NULL,
    ENTRY VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MENURESTRICTIONS PRIMARY KEY(USER, ENTRY),
    CONSTRAINT FK_MENURESTRICTIONS01 FOREIGN KEY(USER) REFERENCES USERS(NAME),
    CONSTRAINT FK_MENURESTRICTIONS02 FOREIGN KEY(ENTRY) REFERENCES MENUENTRIES(TRANSLATIONCODE)
);