DROP TABLE IF EXISTS CONFIGURATION;

CREATE TABLE CONFIGURATION(
    NAME VARCHAR(50),
    VALUE VARCHAR(150),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CONFIGURATION PRIMARY KEY(NAME)
);

DELETE FROM USERS WHERE NAME <> 'Initial';

DELETE FROM ROLES;

INSERT INTO ROLES(ROLE) VALUES ('SuperAdmin');
INSERT INTO ROLES(ROLE) VALUES ('Admin');
INSERT INTO ROLES(ROLE) VALUES ('Editor');
INSERT INTO ROLES(ROLE) VALUES ('Guest');

DROP TABLE IF EXISTS PLUGINS;

CREATE TABLE PLUGINS (
    PLUGIN VARCHAR(100),
    NAME VARCHAR(100),
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PLUGINS PRIMARY KEY(PLUGIN)
);

DROP TABLE IF EXISTS MENURESTRICTIONS;
DROP TABLE IF EXISTS MENUENTRIES;
DROP TABLE IF EXISTS MENUSECTIONS;

CREATE TABLE MENUSECTIONS(
    TRANSLATIONCODE VARCHAR(100) NOT NULL,
    PLUGIN VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MENUSECTIONS PRIMARY KEY(TRANSLATIONCODE),
    CONSTRAINT FK_MENUSECTIONS01 FOREIGN KEY(PLUGIN) REFERENCES PLUGINS(PLUGIN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MENUENTRIES(
    TRANSLATIONCODE VARCHAR(100),
    SLUG VARCHAR(100) NOT NULL,
    SECTION VARCHAR(100),
    PLUGIN VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MENUENTRIES PRIMARY KEY(TRANSLATIONCODE),
    CONSTRAINT FK_MENUENTRIES01 FOREIGN KEY(SECTION) REFERENCES MENUSECTIONS(TRANSLATIONCODE) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_MENUENTRIES02 FOREIGN KEY(PLUGIN) REFERENCES PLUGINS(PLUGIN) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO MENUSECTIONS (TRANSLATIONCODE) VALUES ('menu-section-pages');
INSERT INTO MENUSECTIONS (TRANSLATIONCODE) VALUES ('menu-section-configuration');

INSERT INTO MENUENTRIES (TRANSLATIONCODE, SECTION, SLUG) VALUES ('menu-entries-pages', 'menu-section-pages', '/pages');
INSERT INTO MENUENTRIES (TRANSLATIONCODE, SECTION, SLUG) VALUES ('menu-entries-languages', 'menu-section-configuration', '/languages');

CREATE TABLE MENURESTRICTIONS(
    USER VARCHAR(50) NOT NULL,
    ENTRY VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_MENURESTRICTIONS PRIMARY KEY(USER, ENTRY),
    CONSTRAINT FK_MENURESTRICTIONS01 FOREIGN KEY(USER) REFERENCES USERS(NAME) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_MENURESTRICTIONS02 FOREIGN KEY(ENTRY) REFERENCES MENUENTRIES(TRANSLATIONCODE) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS PAGES;
CREATE TABLE PAGES(
	PAGE INTEGER AUTO_INCREMENT NOT NULL,
    SLUG VARCHAR(100),
    PLUGIN VARCHAR(100),
    CONTENTS TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PAGES PRIMARY KEY(PAGE),
    CONSTRAINT FK_PAGES01 FOREIGN KEY(PLUGIN) REFERENCES PLUGINS(PLUGIN) ON DELETE CASCADE ON UPDATE CASCADE
);